# from https://github.com/gitpod-io/gitpod/pull/6409 for host.gateway.internal zz-_48-_y21-1203-2144
experimentalNetwork: true

# use docker image to persist phpstorm ide settings across new workspace or reboot
#   Simply use `tmy-persist-ide-settings-through-image-for-gitpod` (should be in image already), then get the
#   latest tag name, update below
#   NOTE: in theory should not need the tag name, but seems gitpod is caching image locally, hence to use
#   tag name to ensure latest image is pulled
image: tmy2017/gitpod-pm-with-mysql:ver-1639509397



ports:
  # open browser could be blocked by browser
  - port: 19999
    onOpen: open-browser
  # Laravel server
  - port: 8000
    onOpen: open-preview
  # MySQL server
  - port: 3306
    onOpen: ignore

tasks:
  # launch phpstorm
  - command: tmy-pstorm-launch-GITPOD_REPO_ROOT
  - init: >
      mysql -u root -e "create database example_app" &&
      cp .env.example .env &&
      sed -i "s|APP_URL=|APP_URL=${GITPOD_WORKSPACE_URL}|g" .env &&
      sed -i "s|APP_URL=https://|APP_URL=https://8000-|g" .env &&
      composer install &&
      npm i &&
      php artisan key:generate
    command: >
      php -S 0.0.0.0:8000 -t public

